apiVersion: v1
kind: Service
metadata:
  name: workout-api-service
  namespace: liftlog-apps
spec:
  selector:
    app: workout-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
