apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workout-api
  namespace: liftlog-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default
  source:
    repoURL: https://github.com/sandwh0/liftlog-gitops.git
    targetRevision: main  
    path: apps/workout-api
    
  destination:
    server: https://kubernetes.default.svc
    namespace: liftlog-argo

  syncPolicy:
    automated: {}
